language: objective-c
osx_image: xcode9.4
xcode_project: FUNI.xcodeproj
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
xcode_scheme: FUNITests

deploy:
  provider: script
  script: bash tests.sh
  on:
    branch: develop

branches:
  only:
  - develop

notifications:
  email:
    recipients:
      - hai@flomail.net
    on_success: never
    on_failure: always